[package]
name = "emqx-mqtt-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.11.0"
prost-derive = "0.11.0"
rumqttc = "0.13.0"
tokio = { version = "1.0", features = ["full"] }
rand = "0.8.5"

[build-dependencies]
prost-build = "0.11.0"
